---
abstract: 'a set of objects or scalars with no duplicates and a user-configurable equivalence relation'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0.010
  Test::More: 0.96
  Test::Requires: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Set::Equivalence
name: Set-Equivalence
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  List::MoreUtils: 0.33
  Type::Tiny: 0.016
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Set-Equivalence
  homepage: https://metacpan.org/release/Set-Equivalence
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-set-equivalence
version: 0.000_05
