---
abstract: 'a set of objects or scalars with no duplicates and a user-configurable equivalence relation'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0.010
  Test::More: 0.96
  Test::Requires: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Set-Equivalence
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Set::Equivalence:
    file: lib/Set/Equivalence.pm
    version: 0.003
  Types::Set:
    file: lib/Types/Set.pm
    version: 0.003
requires:
  Exporter::Tiny: 0.026
  List::MoreUtils: 0.33
  Type::Tiny: 0.016
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Set-Equivalence/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Set-Equivalence
  homepage: https://metacpan.org/release/Set-Equivalence
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-set-equivalence
version: 0.003
